# Name
name: Jacob Padilla

# Short bio or description about you (displayed in the header)
description: CSCI-UA 480 Student, Spring 2025

# URL of your avatar or profile pic
avatar: /jpjacobpadilla-weekly/images/icon.png 

# fallback text in case image is not served and/or for screen readers
avatar_alt_text: Avatar

# Use this separator in your blogs to indicate where the abbreviated part ends
excerpt_separator: <!--more-->

footer-links:
  email: jep9670@stern.nyu.edu
  github: jpjacobpadilla
  linkedin: jpjacobpadilla
  stackoverflow: users/21216449/jacob

url: "https://ossd-s25.github.io/jpjacobpadilla-weekly"

baseurl: "/jpjacobpadilla-weekly"


#
# !! You don't need to change any of the configuration flags below !!
#   (but you may, if you know what you are doing)
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
